### ISSUE TITLE
Does not handle Character type

### ISSUE THREAD

**Issue by Luxor** [tednaleid/build-test-data#45]
If a class has Character property then builder generates the following:

```java
Could not find matching constructor for: java.lang.Character()
groovy.lang.GroovyRuntimeException: Could not find matching constructor for: java.lang.Character()
	at grails.buildtestdata.handler.NullableConstraintHandler.determineNonStandardValue(NullableConstraintHandler.groovy:117)
	at grails.buildtestdata.handler.NullableConstraintHandler.handle(NullableConstraintHandler.groovy:21)
	at grails.buildtestdata.DomainInstanceBuilder.createMissingProperty(DomainInstanceBuilder.groovy:198)
	at grails.buildtestdata.DomainInstanceBuilder.populateInstance(DomainInstanceBuilder.groovy:158)
	at grails.buildtestdata.DomainInstanceBuilder.build(DomainInstanceBuilder.groovy:136)
	at grails.buildtestdata.DomainInstanceBuilder.build(DomainInstanceBuilder.groovy:135)
	at grails.buildtestdata.BuildTestDataService.addBuildMethods_closure1(BuildTestDataService.groovy:24)
	at groovy.lang.Closure.call(Closure.java:423)

```

**Comment by longwa** [comment]
Interesting, I've not used a Character type in a domain object. Seems like it should be easy enough to support. If you've taken a stab at it, pull requests are welcome.

**Comment by tednaleid** [comment]
This kind of case is really meant to be dealt with via the `TestDataConfig` providing a default value.  BuildTestData is mostly meant for building domain objects and fields that are commonly stored in databases (strings, numerics, dates) which all have zero-arg constructors.   I'm not sure I understand the use-case where it'd be useful to store a `Character` in a domain object/database, but I think the `TestDataConfig` should let you set this value or others like it where BTD isn't able to create the value for you.
